-- MySQL Script generated by MySQL Workbench
-- Thu May 13 12:21:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cuadros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cuadros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuadros` DEFAULT CHARACTER SET utf8 ;
USE `cuadros` ;

-- -----------------------------------------------------
-- Table `cuadros`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuadros`.`Customer` (
  `dni` VARCHAR(9) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuadros`.`Painting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuadros`.`Painting` (
  `id_painting` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `author` VARCHAR(45) NULL,
  `Customer_dni` VARCHAR(9) NULL,
  PRIMARY KEY (`id_painting`),
  CONSTRAINT `fk_Painting_Customer`
    FOREIGN KEY (`Customer_dni`)
    REFERENCES `cuadros`.`Customer` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cuadros`.`Customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `cuadros`;
INSERT INTO `cuadros`.`Customer` (`dni`, `first_name`, `last_name`) VALUES ('54895478P', 'Ana', 'Vera');
INSERT INTO `cuadros`.`Customer` (`dni`, `first_name`, `last_name`) VALUES ('47587364H', 'María', 'Montilla');
INSERT INTO `cuadros`.`Customer` (`dni`, `first_name`, `last_name`) VALUES ('45122569L', 'Irma', 'De La Cruz');
INSERT INTO `cuadros`.`Customer` (`dni`, `first_name`, `last_name`) VALUES ('45885469K', 'Francisco', 'Montelongo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cuadros`.`Painting`
-- -----------------------------------------------------
START TRANSACTION;
USE `cuadros`;
INSERT INTO `cuadros`.`Painting` (`id_painting`, `price`, `author`, `Customer_dni`) VALUES (541, 90.5, 'Picasso', '54895478P');
INSERT INTO `cuadros`.`Painting` (`id_painting`, `price`, `author`, `Customer_dni`) VALUES (645, 120.35, 'Dalí', NULL);
INSERT INTO `cuadros`.`Painting` (`id_painting`, `price`, `author`, `Customer_dni`) VALUES (745, 578.68, 'Monet', '47587364H');
INSERT INTO `cuadros`.`Painting` (`id_painting`, `price`, `author`, `Customer_dni`) VALUES (231, 1056.21, NULL, NULL);
INSERT INTO `cuadros`.`Painting` (`id_painting`, `price`, `author`, `Customer_dni`) VALUES (258, 2415.87, 'Velázquez', '45122569L');
INSERT INTO `cuadros`.`Painting` (`id_painting`, `price`, `author`, `Customer_dni`) VALUES (476, 1245.89, 'Goya', '45885469K');

COMMIT;

