-- MySQL Script generated by MySQL Workbench
-- Thu May 13 12:22:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vueling
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vueling
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vueling` DEFAULT CHARACTER SET utf8 ;
USE `vueling` ;

-- -----------------------------------------------------
-- Table `vueling`.`Plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueling`.`Plane` (
  `id_plane` INT NOT NULL,
  `capacity` INT NULL,
  `model` VARCHAR(45) NULL,
  PRIMARY KEY (`id_plane`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vueling`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueling`.`Seat` (
  `id_seat` INT NOT NULL,
  `Plane_id_plane` INT NOT NULL,
  PRIMARY KEY (`id_seat`, `Plane_id_plane`),
  CONSTRAINT `fk_Seat_Plane`
    FOREIGN KEY (`Plane_id_plane`)
    REFERENCES `vueling`.`Plane` (`id_plane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `vueling`.`Plane`
-- -----------------------------------------------------
START TRANSACTION;
USE `vueling`;
INSERT INTO `vueling`.`Plane` (`id_plane`, `capacity`, `model`) VALUES (1, 360, 'ATR4785');
INSERT INTO `vueling`.`Plane` (`id_plane`, `capacity`, `model`) VALUES (2, 250, 'AB737');
INSERT INTO `vueling`.`Plane` (`id_plane`, `capacity`, `model`) VALUES (3, 380, 'AB380');
INSERT INTO `vueling`.`Plane` (`id_plane`, `capacity`, `model`) VALUES (4, 346, 'AB747');
INSERT INTO `vueling`.`Plane` (`id_plane`, `capacity`, `model`) VALUES (5, 80, 'ATR6955');

COMMIT;


-- -----------------------------------------------------
-- Data for table `vueling`.`Seat`
-- -----------------------------------------------------
START TRANSACTION;
USE `vueling`;
INSERT INTO `vueling`.`Seat` (`id_seat`, `Plane_id_plane`) VALUES (1, 1);
INSERT INTO `vueling`.`Seat` (`id_seat`, `Plane_id_plane`) VALUES (2, 1);
INSERT INTO `vueling`.`Seat` (`id_seat`, `Plane_id_plane`) VALUES (3, 1);
INSERT INTO `vueling`.`Seat` (`id_seat`, `Plane_id_plane`) VALUES (4, 1);
INSERT INTO `vueling`.`Seat` (`id_seat`, `Plane_id_plane`) VALUES (1, 2);
INSERT INTO `vueling`.`Seat` (`id_seat`, `Plane_id_plane`) VALUES (2, 2);
INSERT INTO `vueling`.`Seat` (`id_seat`, `Plane_id_plane`) VALUES (3, 2);
INSERT INTO `vueling`.`Seat` (`id_seat`, `Plane_id_plane`) VALUES (4, 2);

COMMIT;

